/**
 * Dumb Charadess words, generated from CORPUS-CHARADESS.md.
 *
 * One row is one thing to act out. `difficulty` is how hard it is to ACT, not
 * how obscure it is: "Inception" is famous and still hard, "Hammer" is neither.
 *
 * `aliases` exists because a guess is typed, not spoken. Normalising handles
 * case, spaces and punctuation on its own; aliases cover the rest, where a
 * room would say the right answer out loud and then spell it a second common
 * way. Without them a player loses a point to a keyboard rather than to a bad
 * round.
 */
import type { ContentSeed } from "./types";

export const WORDS: ContentSeed[] = [
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Sholay", region: "india", category: "Movies", difficulty: "easy", metadata: { aliases: ["Sholey"] } },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Hera Pheri", region: "india", category: "Movies", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Andaz Apna Apna", region: "india", category: "Movies", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Jaane Bhi Do Yaaro", region: "india", category: "Movies", difficulty: "hard" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Chupke Chupke", region: "india", category: "Movies", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Golmaal", region: "india", category: "Movies", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Munna Bhai MBBS", region: "india", category: "Movies", difficulty: "easy", metadata: { aliases: ["Munnabhai MBBS"] } },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Lage Raho Munna Bhai", region: "india", category: "Movies", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "3 Idiots", region: "india", category: "Movies", difficulty: "easy", metadata: { aliases: ["Three Idiots"] } },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Phir Hera Pheri", region: "india", category: "Movies", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Welcome", region: "india", category: "Movies", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Dhamaal", region: "india", category: "Movies", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Padosan", region: "india", category: "Movies", difficulty: "hard" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Chalti Ka Naam Gaadi", region: "india", category: "Movies", difficulty: "hard" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Angoor", region: "india", category: "Movies", difficulty: "hard" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Bhool Bhulaiyaa", region: "india", category: "Movies", difficulty: "medium", metadata: { aliases: ["Bhool Bhulaiya"] } },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Dilwale Dulhania Le Jayenge", region: "india", category: "Movies", difficulty: "medium", metadata: { aliases: ["DDLJ"] } },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Kuch Kuch Hota Hai", region: "india", category: "Movies", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Kabhi Khushi Kabhie Gham", region: "india", category: "Movies", difficulty: "medium", metadata: { aliases: ["K3G"] } },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Hum Aapke Hain Koun", region: "india", category: "Movies", difficulty: "medium", metadata: { aliases: ["HAHK"] } },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Maine Pyar Kiya", region: "india", category: "Movies", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Jab We Met", region: "india", category: "Movies", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Yeh Jawaani Hai Deewani", region: "india", category: "Movies", difficulty: "medium", metadata: { aliases: ["YJHD"] } },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Dil Chahta Hai", region: "india", category: "Movies", difficulty: "medium", metadata: { aliases: ["DCH"] } },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Zindagi Na Milegi Dobara", region: "india", category: "Movies", difficulty: "medium", metadata: { aliases: ["ZNMD"] } },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Veer Zaara", region: "india", category: "Movies", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Devdas", region: "india", category: "Movies", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Barfi", region: "india", category: "Movies", difficulty: "medium", metadata: { aliases: ["Barfi!"] } },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Baahubali", region: "india", category: "Movies", difficulty: "easy", metadata: { aliases: ["Bahubali"] } },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "RRR", region: "india", category: "Movies", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "KGF", region: "india", category: "Movies", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Pushpa", region: "india", category: "Movies", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Dangal", region: "india", category: "Movies", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Sultan", region: "india", category: "Movies", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Bhaag Milkha Bhaag", region: "india", category: "Movies", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Gangs of Wasseypur", region: "india", category: "Movies", difficulty: "medium", metadata: { aliases: ["GOW"] } },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Drishyam", region: "india", category: "Movies", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Andhadhun", region: "india", category: "Movies", difficulty: "hard" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Kahaani", region: "india", category: "Movies", difficulty: "medium", metadata: { aliases: ["Kahani"] } },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "A Wednesday", region: "india", category: "Movies", difficulty: "hard" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Special 26", region: "india", category: "Movies", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Rang De Basanti", region: "india", category: "Movies", difficulty: "medium", metadata: { aliases: ["RDB"] } },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Swades", region: "india", category: "Movies", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Lagaan", region: "india", category: "Movies", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Kantara", region: "india", category: "Movies", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Jawan", region: "india", category: "Movies", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Pathaan", region: "india", category: "Movies", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Animal", region: "india", category: "Movies", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Stree", region: "india", category: "Movies", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Tumbbad", region: "india", category: "Movies", difficulty: "hard" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Article 15", region: "india", category: "Movies", difficulty: "hard" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Talaash", region: "india", category: "Movies", difficulty: "hard" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Titanic", region: "global", category: "Movies", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Avatar", region: "global", category: "Movies", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Jurassic Park", region: "global", category: "Movies", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "The Lion King", region: "global", category: "Movies", difficulty: "easy", metadata: { aliases: ["Lion King"] } },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Harry Potter", region: "global", category: "Movies", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Spider Man", region: "global", category: "Movies", difficulty: "easy", metadata: { aliases: ["Spiderman"] } },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Iron Man", region: "global", category: "Movies", difficulty: "easy", metadata: { aliases: ["Ironman"] } },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "The Avengers", region: "global", category: "Movies", difficulty: "easy", metadata: { aliases: ["Avengers"] } },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Inception", region: "global", category: "Movies", difficulty: "hard" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Interstellar", region: "global", category: "Movies", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "The Dark Knight", region: "global", category: "Movies", difficulty: "medium", metadata: { aliases: ["Dark Knight"] } },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Joker", region: "global", category: "Movies", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Squid Game", region: "global", category: "Movies", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Money Heist", region: "global", category: "Movies", difficulty: "medium", metadata: { aliases: ["La Casa de Papel"] } },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Frozen", region: "global", category: "Movies", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Finding Nemo", region: "global", category: "Movies", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Home Alone", region: "global", category: "Movies", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Fast and Furious", region: "global", category: "Movies", difficulty: "easy", metadata: { aliases: ["Fast & Furious"] } },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Mission Impossible", region: "global", category: "Movies", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Kung Fu Panda", region: "global", category: "Movies", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Amitabh Bachchan", region: "india", category: "Celebrities", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Shah Rukh Khan", region: "india", category: "Celebrities", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Salman Khan", region: "india", category: "Celebrities", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Aamir Khan", region: "india", category: "Celebrities", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Akshay Kumar", region: "india", category: "Celebrities", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Ajay Devgn", region: "india", category: "Celebrities", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Hrithik Roshan", region: "india", category: "Celebrities", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Ranveer Singh", region: "india", category: "Celebrities", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Ranbir Kapoor", region: "india", category: "Celebrities", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Deepika Padukone", region: "india", category: "Celebrities", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Alia Bhatt", region: "india", category: "Celebrities", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Kareena Kapoor", region: "india", category: "Celebrities", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Madhuri Dixit", region: "india", category: "Celebrities", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Rekha", region: "india", category: "Celebrities", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Rajinikanth", region: "india", category: "Celebrities", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Kamal Haasan", region: "india", category: "Celebrities", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Allu Arjun", region: "india", category: "Celebrities", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Prabhas", region: "india", category: "Celebrities", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Yash", region: "india", category: "Celebrities", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Nawazuddin Siddiqui", region: "india", category: "Celebrities", difficulty: "hard" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Pankaj Tripathi", region: "india", category: "Celebrities", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Boman Irani", region: "india", category: "Celebrities", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Johnny Lever", region: "india", category: "Celebrities", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Paresh Rawal", region: "india", category: "Celebrities", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Sachin Tendulkar", region: "india", category: "Celebrities", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Virat Kohli", region: "india", category: "Celebrities", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "MS Dhoni", region: "india", category: "Celebrities", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Rohit Sharma", region: "india", category: "Celebrities", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Kapil Dev", region: "india", category: "Celebrities", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Yuvraj Singh", region: "india", category: "Celebrities", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Ravindra Jadeja", region: "india", category: "Celebrities", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Hardik Pandya", region: "india", category: "Celebrities", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "PV Sindhu", region: "india", category: "Celebrities", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Neeraj Chopra", region: "india", category: "Celebrities", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Cristiano Ronaldo", region: "global", category: "Celebrities", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Lionel Messi", region: "global", category: "Celebrities", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Narendra Modi", region: "india", category: "Celebrities", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Rahul Gandhi", region: "india", category: "Celebrities", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "APJ Abdul Kalam", region: "india", category: "Celebrities", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Ratan Tata", region: "india", category: "Celebrities", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Mukesh Ambani", region: "india", category: "Celebrities", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Elon Musk", region: "global", category: "Celebrities", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "event", title: "World Cup 2011 win", region: "india", category: "Events", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "event", title: "1983 World Cup win", region: "india", category: "Events", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "event", title: "Dhoni's last ball six", region: "india", category: "Events", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "event", title: "Chandrayaan 3 landing", region: "india", category: "Events", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "event", title: "Mangalyaan", region: "india", category: "Events", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "event", title: "Demonetisation", region: "india", category: "Events", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "event", title: "COVID lockdown", region: "mixed", category: "Events", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "event", title: "Modi winning the election", region: "india", category: "Events", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "event", title: "Ram Mandir opening", region: "india", category: "Events", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "event", title: "Kumbh Mela", region: "india", category: "Events", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "event", title: "Article 370", region: "india", category: "Events", difficulty: "hard" },
  { gameSlug: "dumb-charadess", contentType: "event", title: "Farmers protest", region: "india", category: "Events", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "event", title: "Kerala floods", region: "india", category: "Events", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "event", title: "Mumbai local floods", region: "india", category: "Events", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "event", title: "Ambani wedding", region: "india", category: "Events", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "event", title: "Anna Hazare protest", region: "india", category: "Events", difficulty: "hard" },
  { gameSlug: "dumb-charadess", contentType: "event", title: "IPL auction", region: "india", category: "Events", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "event", title: "Kabaddi league", region: "india", category: "Events", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "event", title: "Twin towers falling", region: "global", category: "Events", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "event", title: "Twin towers Noida demolition", region: "india", category: "Events", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "event", title: "Will Smith slap", region: "global", category: "Events", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "event", title: "Titanic sinking", region: "global", category: "Events", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "event", title: "Moon landing", region: "global", category: "Events", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "event", title: "Berlin Wall falling", region: "global", category: "Events", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "event", title: "Olympics opening ceremony", region: "global", category: "Events", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "event", title: "Oscars", region: "global", category: "Events", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "event", title: "Eclipse", region: "mixed", category: "Events", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "event", title: "New Year countdown", region: "mixed", category: "Events", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "event", title: "Cricket World Cup final", region: "mixed", category: "Events", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "event", title: "Power cut in the whole colony", region: "india", category: "Events", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Bhuvan Bam", region: "india", category: "Creators", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "CarryMinati", region: "india", category: "Creators", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Prajakta Koli", region: "india", category: "Creators", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Ashish Chanchlani", region: "india", category: "Creators", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Technical Guruji", region: "india", category: "Creators", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Samay Raina", region: "india", category: "Creators", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Tanmay Bhat", region: "india", category: "Creators", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Zakir Khan", region: "india", category: "Creators", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Kapil Sharma", region: "india", category: "Creators", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Kanan Gill", region: "india", category: "Creators", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Biswa Kalyan Rath", region: "india", category: "Creators", difficulty: "hard" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Abhishek Upmanyu", region: "india", category: "Creators", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Munawar Faruqui", region: "india", category: "Creators", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Puneet Superstar", region: "india", category: "Creators", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Abhijeet Dipke", region: "india", category: "Creators", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Dhruv Rathee", region: "india", category: "Creators", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Ranveer Allahbadia", region: "india", category: "Creators", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Mortal", region: "india", category: "Creators", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Scout", region: "india", category: "Creators", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "Total Gaming", region: "india", category: "Creators", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "MrBeast", region: "global", category: "Creators", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "person", title: "PewDiePie", region: "global", category: "Creators", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Maggi", region: "india", category: "Brands", difficulty: "easy", metadata: { aliases: ["Maggie"] } },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Kurkure", region: "india", category: "Brands", difficulty: "easy", metadata: { aliases: ["Kurkurey"] } },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Parle G", region: "india", category: "Brands", difficulty: "easy", metadata: { aliases: ["ParleG"] } },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Amul", region: "india", category: "Brands", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Frooti", region: "india", category: "Brands", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Thums Up", region: "india", category: "Brands", difficulty: "easy", metadata: { aliases: ["ThumsUp"] } },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Rasna", region: "india", category: "Brands", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Bournvita", region: "india", category: "Brands", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Lays", region: "global", category: "Brands", difficulty: "easy", metadata: { aliases: ["Lay's"] } },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Oreo", region: "global", category: "Brands", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Coca Cola", region: "global", category: "Brands", difficulty: "easy", metadata: { aliases: ["Coke"] } },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Nescafe", region: "global", category: "Brands", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Nike", region: "global", category: "Brands", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Adidas", region: "global", category: "Brands", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Apple", region: "global", category: "Brands", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "WhatsApp", region: "global", category: "Brands", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Instagram", region: "global", category: "Brands", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Netflix", region: "global", category: "Brands", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Hammer", region: "mixed", category: "Objects", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Pressure cooker", region: "india", category: "Objects", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Ceiling fan", region: "india", category: "Objects", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Auto rickshaw", region: "india", category: "Objects", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Cricket bat", region: "india", category: "Objects", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Umbrella", region: "mixed", category: "Objects", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Toothbrush", region: "mixed", category: "Objects", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Sewing machine", region: "mixed", category: "Objects", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Washing machine", region: "mixed", category: "Objects", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Pimple", region: "mixed", category: "Objects", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Mosquito coil", region: "india", category: "Objects", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Bucket bath", region: "india", category: "Objects", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Selfie stick", region: "mixed", category: "Objects", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Earphones", region: "mixed", category: "Objects", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Water bottle", region: "mixed", category: "Objects", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Ladder", region: "mixed", category: "Objects", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Suitcase", region: "mixed", category: "Objects", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Scissors", region: "mixed", category: "Objects", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Traffic signal", region: "mixed", category: "Objects", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Vending machine", region: "global", category: "Objects", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Sneeze", region: "mixed", category: "Words", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Yawn", region: "mixed", category: "Words", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Hiccup", region: "mixed", category: "Words", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Snoring", region: "mixed", category: "Words", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Tickle", region: "mixed", category: "Words", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Swimming", region: "mixed", category: "Words", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Juggling", region: "mixed", category: "Words", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Tiptoe", region: "mixed", category: "Words", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Shivering", region: "mixed", category: "Words", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Sunburn", region: "mixed", category: "Words", difficulty: "hard" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Traffic jam", region: "india", category: "Words", difficulty: "easy" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Queue", region: "mixed", category: "Words", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Haggling", region: "india", category: "Words", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Overacting", region: "india", category: "Words", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Bargaining at a shop", region: "india", category: "Words", difficulty: "medium" },
  { gameSlug: "dumb-charadess", contentType: "phrase", title: "Missing the train", region: "mixed", category: "Words", difficulty: "medium" },
];
