/**
 * Guess the Liar questions, generated from CORPUS-LIAR.md.
 *
 * Every one of these is an opinion. A question with a correct answer would end
 * the round in a second, because the liar would be the only person who got it
 * wrong. `adult: true` questions stay out unless the host turns them on.
 */
import type { ContentSeed } from "./types";

export const QUESTIONS: ContentSeed[] = [
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best street food in the country, one dish, no hedging", region: "mixed", category: "Food", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The most overrated dish in India", region: "mixed", category: "Food", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best biryani city, and you have to commit", region: "mixed", category: "Food", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Chai or coffee, and why the other one is wrong", region: "mixed", category: "Food", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The one food you could eat every day for a year", region: "mixed", category: "Food", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best midnight snack", region: "mixed", category: "Food", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The dish your family makes that you secretly do not like", region: "mixed", category: "Food", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Pineapple on pizza: defend your position", region: "mixed", category: "Food", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best Maggi hack you have", region: "mixed", category: "Food", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best Indian sweet, one only", region: "mixed", category: "Food", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The most overrated restaurant chain", region: "mixed", category: "Food", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best paratha filling", region: "mixed", category: "Food", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "What you order at a dhaba at two in the morning", region: "mixed", category: "Food", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best regional cuisine in India, pick one state", region: "mixed", category: "Food", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The food you always steal off someone else's plate", region: "mixed", category: "Food", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Momos or rolls", region: "mixed", category: "Food", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The most disappointing thing you have eaten abroad", region: "mixed", category: "Food", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best thing to eat on a train", region: "mixed", category: "Food", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The drink you want on the hottest day of the year", region: "mixed", category: "Food", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best thing to eat when you are sad", region: "mixed", category: "Food", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best cricketer ever, one name", region: "india", category: "Cricket and sport", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best Indian captain of all time", region: "india", category: "Cricket and sport", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The most overrated player in the IPL", region: "india", category: "Cricket and sport", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Kohli or Sachin, pick and defend", region: "india", category: "Cricket and sport", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best IPL team, no fence-sitting", region: "india", category: "Cricket and sport", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The greatest moment in Indian cricket", region: "india", category: "Cricket and sport", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best fast bowler you have watched play", region: "india", category: "Cricket and sport", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Messi or Ronaldo", region: "india", category: "Cricket and sport", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The sport you would be good at if you trained for a year", region: "india", category: "Cricket and sport", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The most boring sport to watch", region: "india", category: "Cricket and sport", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best commentator voice in the game", region: "india", category: "Cricket and sport", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The best World Cup final you have seen", region: "india", category: "Cricket and sport", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Who should be opening for India right now", region: "india", category: "Cricket and sport", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The most annoying fan base", region: "india", category: "Cricket and sport", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best comeback you have watched live", region: "india", category: "Cricket and sport", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The player you would pay to watch bat for one over", region: "india", category: "Cricket and sport", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best Hindi film ever made", region: "india", category: "Film", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The most overrated actor working today", region: "india", category: "Film", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best Shah Rukh Khan film", region: "india", category: "Film", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The film you have rewatched the most", region: "india", category: "Film", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best villain in Indian cinema", region: "india", category: "Film", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The worst film you have paid money for", region: "india", category: "Film", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best South Indian film of the last five years", region: "india", category: "Film", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The most quotable line ever written for a Hindi film", region: "india", category: "Film", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best film soundtrack", region: "india", category: "Film", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The actor who should take a long break", region: "india", category: "Film", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best Hindi web series", region: "india", category: "Film", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The film everybody loves that bores you", region: "india", category: "Film", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best on-screen pair", region: "india", category: "Film", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The best debut performance you have seen", region: "india", category: "Film", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best film to watch at three in the morning", region: "india", category: "Film", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The remake that should never have been made", region: "india", category: "Film", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best Indian meme ever made", region: "mixed", category: "Internet", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The meme that needs to be retired", region: "mixed", category: "Internet", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best YouTube channel in India", region: "mixed", category: "Internet", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The app you waste the most time on", region: "mixed", category: "Internet", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The most annoying trend on Instagram", region: "mixed", category: "Internet", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best roast you have seen online", region: "mixed", category: "Internet", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The influencer you would unfollow first", region: "mixed", category: "Internet", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The funniest account you follow", region: "mixed", category: "Internet", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best podcast going right now", region: "mixed", category: "Internet", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The comment section you cannot stay out of", region: "mixed", category: "Internet", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The most overrated gadget you own", region: "mixed", category: "Internet", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best group chat name you have ever had", region: "mixed", category: "Internet", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The last thing online that made you laugh out loud", region: "mixed", category: "Internet", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best emoji, and it is not close", region: "mixed", category: "Internet", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The password habit you know is a bad idea", region: "mixed", category: "Internet", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Your most-used app that you would be embarrassed to show", region: "mixed", category: "Internet", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Who here would last longest in a zombie apocalypse", region: "mixed", category: "This room", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Who in this room is most likely to get famous", region: "mixed", category: "This room", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Who is the worst driver here", region: "mixed", category: "This room", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Who would you call at three in the morning", region: "mixed", category: "This room", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Who takes the longest to get ready", region: "mixed", category: "This room", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Who lies the most in this room", region: "mixed", category: "This room", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Who is the funniest person here", region: "mixed", category: "This room", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Who wins a fight in this room, no weapons", region: "mixed", category: "This room", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Who spends the most on food delivery", region: "mixed", category: "This room", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Who is most likely to move abroad", region: "mixed", category: "This room", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Who has the worst taste in music", region: "mixed", category: "This room", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Who would forget your birthday", region: "mixed", category: "This room", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Who is the best cook here", region: "mixed", category: "This room", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Who checks their phone the most", region: "mixed", category: "This room", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Who would you trust with your phone unlocked", region: "mixed", category: "This room", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Who here gives the worst advice", region: "mixed", category: "This room", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Who would survive one week without the internet", region: "mixed", category: "This room", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Who is going to be late to their own wedding", region: "mixed", category: "This room", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The most overrated thing about being an adult", region: "mixed", category: "Hot takes", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best decade for music", region: "mixed", category: "Hot takes", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Money or free time, pick one", region: "mixed", category: "Hot takes", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The habit you would drop tomorrow if you could", region: "mixed", category: "Hot takes", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The best age to be", region: "mixed", category: "Hot takes", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The most useless thing you were taught in school", region: "mixed", category: "Hot takes", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best advice anybody has given you", region: "mixed", category: "Hot takes", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The thing everyone loves that you do not get", region: "mixed", category: "Hot takes", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Morning person or night person, and why the other one is wrong", region: "mixed", category: "Hot takes", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best way to spend a Sunday", region: "mixed", category: "Hot takes", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The purchase you regret most", region: "mixed", category: "Hot takes", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Window seat or aisle", region: "mixed", category: "Hot takes", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The one rule you would make law tomorrow", region: "mixed", category: "Hot takes", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best gift you have been given", region: "mixed", category: "Hot takes", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The job you would do if money did not matter", region: "mixed", category: "Hot takes", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Cats or dogs, commit", region: "mixed", category: "Hot takes", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The most overrated festival", region: "mixed", category: "Hot takes", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best thing about your home town", region: "mixed", category: "Hot takes", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The talent you wish you had", region: "mixed", category: "Hot takes", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "What you would do with one completely free hour right now", region: "mixed", category: "Hot takes", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best city in India to actually live in", region: "mixed", category: "Places", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The most overrated tourist spot in the country", region: "mixed", category: "Places", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best beach you have been to", region: "mixed", category: "Places", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Mountains or beach", region: "mixed", category: "Places", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The city you could never live in", region: "mixed", category: "Places", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best road trip in India", region: "mixed", category: "Places", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The country you want to see first", region: "mixed", category: "Places", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best place in your city for a walk", region: "mixed", category: "Places", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The most beautiful place you have seen in person", region: "mixed", category: "Places", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best month of the year where you live", region: "mixed", category: "Places", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Where you would go to disappear for a month", region: "mixed", category: "Places", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The worst place you have spent a night", region: "mixed", category: "Places", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best place in your city to eat at midnight", region: "mixed", category: "Places", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The trip you keep saying you will take and never do", region: "mixed", category: "Places", },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best place to make out", region: "mixed", category: "Spicy", metadata: { adult: true }, },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The worst date you have been on", region: "mixed", category: "Spicy", metadata: { adult: true }, },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Your type, in three words", region: "mixed", category: "Spicy", metadata: { adult: true }, },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The most attractive quality in a person", region: "mixed", category: "Spicy", metadata: { adult: true }, },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Your biggest turn-off", region: "mixed", category: "Spicy", metadata: { adult: true }, },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The worst pickup line you have used or had used on you", region: "mixed", category: "Spicy", metadata: { adult: true }, },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The most embarrassing thing in your search history", region: "mixed", category: "Spicy", metadata: { adult: true }, },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Best flirting move you have", region: "mixed", category: "Spicy", metadata: { adult: true }, },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The celebrity you get one free pass for", region: "mixed", category: "Spicy", metadata: { adult: true }, },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Your worst kissing story", region: "mixed", category: "Spicy", metadata: { adult: true }, },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "What you would lie about on a dating app", region: "mixed", category: "Spicy", metadata: { adult: true }, },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The most awkward place you have been walked in on", region: "mixed", category: "Spicy", metadata: { adult: true }, },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "Your biggest ick", region: "mixed", category: "Spicy", metadata: { adult: true }, },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The worst decision you have made after a drink", region: "mixed", category: "Spicy", metadata: { adult: true }, },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The one text you wish you could unsend", region: "mixed", category: "Spicy", metadata: { adult: true }, },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The friend's ex you would actually go out with", region: "mixed", category: "Spicy", metadata: { adult: true }, },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "How long you have gone without telling anyone something", region: "mixed", category: "Spicy", metadata: { adult: true }, },
  { gameSlug: "guess-the-liar", contentType: "prompt", title: "The compliment you fish for", region: "mixed", category: "Spicy", metadata: { adult: true }, },
];
