/**
 * Traitors name pairs, generated from CORPUS.md and approved before seeding.
 *
 * Pairs are stored symmetrically as `a` and `b`. The game decides at deal time
 * which side is the traitor, so nobody learns that one name is always the odd
 * one out. `adult: true` pairs stay out unless the host turns them on.
 */
import type { ContentSeed } from "./types";

export const PAIRS: ContentSeed[] = [
  { gameSlug: "traitors", contentType: "pair", title: "Virat Kohli / Rohit Sharma", region: "india", category: "Cricket, India", difficulty: "easy", metadata: { a: "Virat Kohli", b: "Rohit Sharma" } },
  { gameSlug: "traitors", contentType: "pair", title: "MS Dhoni / Gautam Gambhir", region: "india", category: "Cricket, India", difficulty: "easy", metadata: { a: "MS Dhoni", b: "Gautam Gambhir" } },
  { gameSlug: "traitors", contentType: "pair", title: "Sachin Tendulkar / Rahul Dravid", region: "india", category: "Cricket, India", difficulty: "easy", metadata: { a: "Sachin Tendulkar", b: "Rahul Dravid" } },
  { gameSlug: "traitors", contentType: "pair", title: "Sourav Ganguly / VVS Laxman", region: "india", category: "Cricket, India", difficulty: "medium", metadata: { a: "Sourav Ganguly", b: "VVS Laxman" } },
  { gameSlug: "traitors", contentType: "pair", title: "Jasprit Bumrah / Mohammed Shami", region: "india", category: "Cricket, India", difficulty: "easy", metadata: { a: "Jasprit Bumrah", b: "Mohammed Shami" } },
  { gameSlug: "traitors", contentType: "pair", title: "Hardik Pandya / Ravindra Jadeja", region: "india", category: "Cricket, India", difficulty: "easy", metadata: { a: "Hardik Pandya", b: "Ravindra Jadeja" } },
  { gameSlug: "traitors", contentType: "pair", title: "Yuvraj Singh / Suresh Raina", region: "india", category: "Cricket, India", difficulty: "easy", metadata: { a: "Yuvraj Singh", b: "Suresh Raina" } },
  { gameSlug: "traitors", contentType: "pair", title: "KL Rahul / Shikhar Dhawan", region: "india", category: "Cricket, India", difficulty: "easy", metadata: { a: "KL Rahul", b: "Shikhar Dhawan" } },
  { gameSlug: "traitors", contentType: "pair", title: "Rishabh Pant / Sanju Samson", region: "india", category: "Cricket, India", difficulty: "easy", metadata: { a: "Rishabh Pant", b: "Sanju Samson" } },
  { gameSlug: "traitors", contentType: "pair", title: "Anil Kumble / Harbhajan Singh", region: "india", category: "Cricket, India", difficulty: "medium", metadata: { a: "Anil Kumble", b: "Harbhajan Singh" } },
  { gameSlug: "traitors", contentType: "pair", title: "Zaheer Khan / Ishant Sharma", region: "india", category: "Cricket, India", difficulty: "medium", metadata: { a: "Zaheer Khan", b: "Ishant Sharma" } },
  { gameSlug: "traitors", contentType: "pair", title: "Shubman Gill / Yashasvi Jaiswal", region: "india", category: "Cricket, India", difficulty: "easy", metadata: { a: "Shubman Gill", b: "Yashasvi Jaiswal" } },
  { gameSlug: "traitors", contentType: "pair", title: "Steve Smith / Joe Root", region: "global", category: "Cricket, global", difficulty: "easy", metadata: { a: "Steve Smith", b: "Joe Root" } },
  { gameSlug: "traitors", contentType: "pair", title: "Ben Stokes / Kane Williamson", region: "global", category: "Cricket, global", difficulty: "medium", metadata: { a: "Ben Stokes", b: "Kane Williamson" } },
  { gameSlug: "traitors", contentType: "pair", title: "Shane Warne / Muttiah Muralitharan", region: "global", category: "Cricket, global", difficulty: "medium", metadata: { a: "Shane Warne", b: "Muttiah Muralitharan" } },
  { gameSlug: "traitors", contentType: "pair", title: "Ricky Ponting / Brian Lara", region: "global", category: "Cricket, global", difficulty: "medium", metadata: { a: "Ricky Ponting", b: "Brian Lara" } },
  { gameSlug: "traitors", contentType: "pair", title: "AB de Villiers / Chris Gayle", region: "global", category: "Cricket, global", difficulty: "easy", metadata: { a: "AB de Villiers", b: "Chris Gayle" } },
  { gameSlug: "traitors", contentType: "pair", title: "Babar Azam / Mohammad Rizwan", region: "global", category: "Cricket, global", difficulty: "easy", metadata: { a: "Babar Azam", b: "Mohammad Rizwan" } },
  { gameSlug: "traitors", contentType: "pair", title: "Wasim Akram / Waqar Younis", region: "global", category: "Cricket, global", difficulty: "hard", metadata: { a: "Wasim Akram", b: "Waqar Younis" } },
  { gameSlug: "traitors", contentType: "pair", title: "Jacques Kallis / Shaun Pollock", region: "global", category: "Cricket, global", difficulty: "hard", metadata: { a: "Jacques Kallis", b: "Shaun Pollock" } },
  { gameSlug: "traitors", contentType: "pair", title: "Lionel Messi / Neymar", region: "global", category: "Football", difficulty: "easy", metadata: { a: "Lionel Messi", b: "Neymar" } },
  { gameSlug: "traitors", contentType: "pair", title: "Kylian Mbappé / Cristiano Ronaldo", region: "global", category: "Football", difficulty: "easy", metadata: { a: "Kylian Mbappé", b: "Cristiano Ronaldo" } },
  { gameSlug: "traitors", contentType: "pair", title: "Zinedine Zidane / Ronaldinho", region: "global", category: "Football", difficulty: "medium", metadata: { a: "Zinedine Zidane", b: "Ronaldinho" } },
  { gameSlug: "traitors", contentType: "pair", title: "Erling Haaland / Robert Lewandowski", region: "global", category: "Football", difficulty: "easy", metadata: { a: "Erling Haaland", b: "Robert Lewandowski" } },
  { gameSlug: "traitors", contentType: "pair", title: "Xavi / Andrés Iniesta", region: "global", category: "Football", difficulty: "hard", metadata: { a: "Xavi", b: "Andrés Iniesta" } },
  { gameSlug: "traitors", contentType: "pair", title: "Sergio Ramos / Gerard Piqué", region: "global", category: "Football", difficulty: "medium", metadata: { a: "Sergio Ramos", b: "Gerard Piqué" } },
  { gameSlug: "traitors", contentType: "pair", title: "Mohamed Salah / Sadio Mané", region: "global", category: "Football", difficulty: "easy", metadata: { a: "Mohamed Salah", b: "Sadio Mané" } },
  { gameSlug: "traitors", contentType: "pair", title: "Pep Guardiola / Jürgen Klopp", region: "global", category: "Football", difficulty: "easy", metadata: { a: "Pep Guardiola", b: "Jürgen Klopp" } },
  { gameSlug: "traitors", contentType: "pair", title: "Sunil Chhetri / Bhaichung Bhutia", region: "india", category: "Football", difficulty: "medium", metadata: { a: "Sunil Chhetri", b: "Bhaichung Bhutia" } },
  { gameSlug: "traitors", contentType: "pair", title: "Shah Rukh Khan / Salman Khan", region: "india", category: "Bollywood", difficulty: "easy", metadata: { a: "Shah Rukh Khan", b: "Salman Khan" } },
  { gameSlug: "traitors", contentType: "pair", title: "Aamir Khan / Akshay Kumar", region: "india", category: "Bollywood", difficulty: "easy", metadata: { a: "Aamir Khan", b: "Akshay Kumar" } },
  { gameSlug: "traitors", contentType: "pair", title: "Deepika Padukone / Priyanka Chopra", region: "india", category: "Bollywood", difficulty: "easy", metadata: { a: "Deepika Padukone", b: "Priyanka Chopra" } },
  { gameSlug: "traitors", contentType: "pair", title: "Alia Bhatt / Katrina Kaif", region: "india", category: "Bollywood", difficulty: "easy", metadata: { a: "Alia Bhatt", b: "Katrina Kaif" } },
  { gameSlug: "traitors", contentType: "pair", title: "Ranbir Kapoor / Ranveer Singh", region: "india", category: "Bollywood", difficulty: "easy", metadata: { a: "Ranbir Kapoor", b: "Ranveer Singh" } },
  { gameSlug: "traitors", contentType: "pair", title: "Ajay Devgn / Sunny Deol", region: "india", category: "Bollywood", difficulty: "medium", metadata: { a: "Ajay Devgn", b: "Sunny Deol" } },
  { gameSlug: "traitors", contentType: "pair", title: "Kareena Kapoor / Karisma Kapoor", region: "india", category: "Bollywood", difficulty: "hard", metadata: { a: "Kareena Kapoor", b: "Karisma Kapoor" } },
  { gameSlug: "traitors", contentType: "pair", title: "Hrithik Roshan / Tiger Shroff", region: "india", category: "Bollywood", difficulty: "easy", metadata: { a: "Hrithik Roshan", b: "Tiger Shroff" } },
  { gameSlug: "traitors", contentType: "pair", title: "Amitabh Bachchan / Dharmendra", region: "india", category: "Bollywood", difficulty: "medium", metadata: { a: "Amitabh Bachchan", b: "Dharmendra" } },
  { gameSlug: "traitors", contentType: "pair", title: "Madhuri Dixit / Sridevi", region: "india", category: "Bollywood", difficulty: "medium", metadata: { a: "Madhuri Dixit", b: "Sridevi" } },
  { gameSlug: "traitors", contentType: "pair", title: "Nawazuddin Siddiqui / Pankaj Tripathi", region: "india", category: "Bollywood", difficulty: "easy", metadata: { a: "Nawazuddin Siddiqui", b: "Pankaj Tripathi" } },
  { gameSlug: "traitors", contentType: "pair", title: "Rajinikanth / Kamal Haasan", region: "india", category: "Bollywood", difficulty: "medium", metadata: { a: "Rajinikanth", b: "Kamal Haasan" } },
  { gameSlug: "traitors", contentType: "pair", title: "Kim Kardashian / Kylie Jenner", region: "global", category: "Global celebrities", difficulty: "easy", metadata: { a: "Kim Kardashian", b: "Kylie Jenner" } },
  { gameSlug: "traitors", contentType: "pair", title: "Brad Pitt / Leonardo DiCaprio", region: "global", category: "Global celebrities", difficulty: "easy", metadata: { a: "Brad Pitt", b: "Leonardo DiCaprio" } },
  { gameSlug: "traitors", contentType: "pair", title: "Tom Cruise / Tom Hanks", region: "global", category: "Global celebrities", difficulty: "medium", metadata: { a: "Tom Cruise", b: "Tom Hanks" } },
  { gameSlug: "traitors", contentType: "pair", title: "Taylor Swift / Ariana Grande", region: "global", category: "Global celebrities", difficulty: "easy", metadata: { a: "Taylor Swift", b: "Ariana Grande" } },
  { gameSlug: "traitors", contentType: "pair", title: "Beyoncé / Rihanna", region: "global", category: "Global celebrities", difficulty: "easy", metadata: { a: "Beyoncé", b: "Rihanna" } },
  { gameSlug: "traitors", contentType: "pair", title: "Dwayne Johnson / Vin Diesel", region: "global", category: "Global celebrities", difficulty: "easy", metadata: { a: "Dwayne Johnson", b: "Vin Diesel" } },
  { gameSlug: "traitors", contentType: "pair", title: "Chris Evans / Chris Hemsworth", region: "global", category: "Global celebrities", difficulty: "easy", metadata: { a: "Chris Evans", b: "Chris Hemsworth" } },
  { gameSlug: "traitors", contentType: "pair", title: "Emma Watson / Emma Stone", region: "global", category: "Global celebrities", difficulty: "medium", metadata: { a: "Emma Watson", b: "Emma Stone" } },
  { gameSlug: "traitors", contentType: "pair", title: "Drake / Kanye West", region: "global", category: "Global celebrities", difficulty: "medium", metadata: { a: "Drake", b: "Kanye West" } },
  { gameSlug: "traitors", contentType: "pair", title: "Justin Bieber / Shawn Mendes", region: "global", category: "Global celebrities", difficulty: "easy", metadata: { a: "Justin Bieber", b: "Shawn Mendes" } },
  { gameSlug: "traitors", contentType: "pair", title: "Jeff Bezos / Elon Musk", region: "mixed", category: "Business and tech", difficulty: "easy", metadata: { a: "Jeff Bezos", b: "Elon Musk" } },
  { gameSlug: "traitors", contentType: "pair", title: "Bill Gates / Steve Jobs", region: "mixed", category: "Business and tech", difficulty: "easy", metadata: { a: "Bill Gates", b: "Steve Jobs" } },
  { gameSlug: "traitors", contentType: "pair", title: "Mark Zuckerberg / Jack Dorsey", region: "mixed", category: "Business and tech", difficulty: "medium", metadata: { a: "Mark Zuckerberg", b: "Jack Dorsey" } },
  { gameSlug: "traitors", contentType: "pair", title: "Mukesh Ambani / Gautam Adani", region: "mixed", category: "Business and tech", difficulty: "easy", metadata: { a: "Mukesh Ambani", b: "Gautam Adani" } },
  { gameSlug: "traitors", contentType: "pair", title: "Ratan Tata / Anand Mahindra", region: "mixed", category: "Business and tech", difficulty: "medium", metadata: { a: "Ratan Tata", b: "Anand Mahindra" } },
  { gameSlug: "traitors", contentType: "pair", title: "Sundar Pichai / Satya Nadella", region: "mixed", category: "Business and tech", difficulty: "easy", metadata: { a: "Sundar Pichai", b: "Satya Nadella" } },
  { gameSlug: "traitors", contentType: "pair", title: "Warren Buffett / Charlie Munger", region: "mixed", category: "Business and tech", difficulty: "hard", metadata: { a: "Warren Buffett", b: "Charlie Munger" } },
  { gameSlug: "traitors", contentType: "pair", title: "Vijay Shekhar Sharma / Byju Raveendran", region: "mixed", category: "Business and tech", difficulty: "hard", metadata: { a: "Vijay Shekhar Sharma", b: "Byju Raveendran" } },
  { gameSlug: "traitors", contentType: "pair", title: "Narendra Modi / Rahul Gandhi", region: "mixed", category: "Politics", difficulty: "easy", metadata: { a: "Narendra Modi", b: "Rahul Gandhi" } },
  { gameSlug: "traitors", contentType: "pair", title: "Arvind Kejriwal / Yogi Adityanath", region: "mixed", category: "Politics", difficulty: "easy", metadata: { a: "Arvind Kejriwal", b: "Yogi Adityanath" } },
  { gameSlug: "traitors", contentType: "pair", title: "Jawaharlal Nehru / Sardar Patel", region: "mixed", category: "Politics", difficulty: "medium", metadata: { a: "Jawaharlal Nehru", b: "Sardar Patel" } },
  { gameSlug: "traitors", contentType: "pair", title: "Barack Obama / Joe Biden", region: "mixed", category: "Politics", difficulty: "easy", metadata: { a: "Barack Obama", b: "Joe Biden" } },
  { gameSlug: "traitors", contentType: "pair", title: "Donald Trump / Boris Johnson", region: "mixed", category: "Politics", difficulty: "medium", metadata: { a: "Donald Trump", b: "Boris Johnson" } },
  { gameSlug: "traitors", contentType: "pair", title: "Indira Gandhi / Margaret Thatcher", region: "mixed", category: "Politics", difficulty: "medium", metadata: { a: "Indira Gandhi", b: "Margaret Thatcher" } },
  { gameSlug: "traitors", contentType: "pair", title: "Delhi / Mumbai", region: "india", category: "Indian cities", difficulty: "easy", metadata: { a: "Delhi", b: "Mumbai" } },
  { gameSlug: "traitors", contentType: "pair", title: "Bangalore / Hyderabad", region: "india", category: "Indian cities", difficulty: "easy", metadata: { a: "Bangalore", b: "Hyderabad" } },
  { gameSlug: "traitors", contentType: "pair", title: "Chennai / Kolkata", region: "india", category: "Indian cities", difficulty: "easy", metadata: { a: "Chennai", b: "Kolkata" } },
  { gameSlug: "traitors", contentType: "pair", title: "Pune / Ahmedabad", region: "india", category: "Indian cities", difficulty: "medium", metadata: { a: "Pune", b: "Ahmedabad" } },
  { gameSlug: "traitors", contentType: "pair", title: "Jaipur / Udaipur", region: "india", category: "Indian cities", difficulty: "medium", metadata: { a: "Jaipur", b: "Udaipur" } },
  { gameSlug: "traitors", contentType: "pair", title: "Goa / Kerala", region: "india", category: "Indian cities", difficulty: "easy", metadata: { a: "Goa", b: "Kerala" } },
  { gameSlug: "traitors", contentType: "pair", title: "Lucknow / Varanasi", region: "india", category: "Indian cities", difficulty: "medium", metadata: { a: "Lucknow", b: "Varanasi" } },
  { gameSlug: "traitors", contentType: "pair", title: "Shimla / Manali", region: "india", category: "Indian cities", difficulty: "easy", metadata: { a: "Shimla", b: "Manali" } },
  { gameSlug: "traitors", contentType: "pair", title: "Chandigarh / Dehradun", region: "india", category: "Indian cities", difficulty: "hard", metadata: { a: "Chandigarh", b: "Dehradun" } },
  { gameSlug: "traitors", contentType: "pair", title: "Kochi / Mysore", region: "india", category: "Indian cities", difficulty: "hard", metadata: { a: "Kochi", b: "Mysore" } },
  { gameSlug: "traitors", contentType: "pair", title: "New York / Los Angeles", region: "global", category: "World cities", difficulty: "easy", metadata: { a: "New York", b: "Los Angeles" } },
  { gameSlug: "traitors", contentType: "pair", title: "London / Paris", region: "global", category: "World cities", difficulty: "easy", metadata: { a: "London", b: "Paris" } },
  { gameSlug: "traitors", contentType: "pair", title: "Tokyo / Seoul", region: "global", category: "World cities", difficulty: "easy", metadata: { a: "Tokyo", b: "Seoul" } },
  { gameSlug: "traitors", contentType: "pair", title: "Dubai / Singapore", region: "global", category: "World cities", difficulty: "easy", metadata: { a: "Dubai", b: "Singapore" } },
  { gameSlug: "traitors", contentType: "pair", title: "Sydney / Melbourne", region: "global", category: "World cities", difficulty: "medium", metadata: { a: "Sydney", b: "Melbourne" } },
  { gameSlug: "traitors", contentType: "pair", title: "Rome / Barcelona", region: "global", category: "World cities", difficulty: "medium", metadata: { a: "Rome", b: "Barcelona" } },
  { gameSlug: "traitors", contentType: "pair", title: "Blanket / Pillow", region: "mixed", category: "Household objects", difficulty: "easy", metadata: { a: "Blanket", b: "Pillow" } },
  { gameSlug: "traitors", contentType: "pair", title: "Window / Door", region: "mixed", category: "Household objects", difficulty: "easy", metadata: { a: "Window", b: "Door" } },
  { gameSlug: "traitors", contentType: "pair", title: "Spoon / Fork", region: "mixed", category: "Household objects", difficulty: "easy", metadata: { a: "Spoon", b: "Fork" } },
  { gameSlug: "traitors", contentType: "pair", title: "Chair / Sofa", region: "mixed", category: "Household objects", difficulty: "easy", metadata: { a: "Chair", b: "Sofa" } },
  { gameSlug: "traitors", contentType: "pair", title: "Mirror / Comb", region: "mixed", category: "Household objects", difficulty: "medium", metadata: { a: "Mirror", b: "Comb" } },
  { gameSlug: "traitors", contentType: "pair", title: "Fan / Air conditioner", region: "mixed", category: "Household objects", difficulty: "easy", metadata: { a: "Fan", b: "Air conditioner" } },
  { gameSlug: "traitors", contentType: "pair", title: "Bucket / Mug", region: "mixed", category: "Household objects", difficulty: "easy", metadata: { a: "Bucket", b: "Mug" } },
  { gameSlug: "traitors", contentType: "pair", title: "Soap / Shampoo", region: "mixed", category: "Household objects", difficulty: "easy", metadata: { a: "Soap", b: "Shampoo" } },
  { gameSlug: "traitors", contentType: "pair", title: "Towel / Napkin", region: "mixed", category: "Household objects", difficulty: "medium", metadata: { a: "Towel", b: "Napkin" } },
  { gameSlug: "traitors", contentType: "pair", title: "Charger / Power bank", region: "mixed", category: "Household objects", difficulty: "easy", metadata: { a: "Charger", b: "Power bank" } },
  { gameSlug: "traitors", contentType: "pair", title: "Fridge / Microwave", region: "mixed", category: "Household objects", difficulty: "easy", metadata: { a: "Fridge", b: "Microwave" } },
  { gameSlug: "traitors", contentType: "pair", title: "Broom / Mop", region: "mixed", category: "Household objects", difficulty: "easy", metadata: { a: "Broom", b: "Mop" } },
  { gameSlug: "traitors", contentType: "pair", title: "Bedsheet / Curtain", region: "mixed", category: "Household objects", difficulty: "medium", metadata: { a: "Bedsheet", b: "Curtain" } },
  { gameSlug: "traitors", contentType: "pair", title: "Slippers / Shoes", region: "mixed", category: "Household objects", difficulty: "easy", metadata: { a: "Slippers", b: "Shoes" } },
  { gameSlug: "traitors", contentType: "pair", title: "College / School", region: "mixed", category: "General life", difficulty: "easy", metadata: { a: "College", b: "School" } },
  { gameSlug: "traitors", contentType: "pair", title: "Girlfriend / Boyfriend", region: "mixed", category: "General life", difficulty: "easy", metadata: { a: "Girlfriend", b: "Boyfriend" } },
  { gameSlug: "traitors", contentType: "pair", title: "Salary / Pocket money", region: "mixed", category: "General life", difficulty: "easy", metadata: { a: "Salary", b: "Pocket money" } },
  { gameSlug: "traitors", contentType: "pair", title: "Monday / Sunday", region: "mixed", category: "General life", difficulty: "easy", metadata: { a: "Monday", b: "Sunday" } },
  { gameSlug: "traitors", contentType: "pair", title: "Exam / Interview", region: "mixed", category: "General life", difficulty: "easy", metadata: { a: "Exam", b: "Interview" } },
  { gameSlug: "traitors", contentType: "pair", title: "Wedding / Engagement", region: "mixed", category: "General life", difficulty: "easy", metadata: { a: "Wedding", b: "Engagement" } },
  { gameSlug: "traitors", contentType: "pair", title: "Rent / EMI", region: "mixed", category: "General life", difficulty: "medium", metadata: { a: "Rent", b: "EMI" } },
  { gameSlug: "traitors", contentType: "pair", title: "Bus / Train", region: "mixed", category: "General life", difficulty: "easy", metadata: { a: "Bus", b: "Train" } },
  { gameSlug: "traitors", contentType: "pair", title: "Doctor / Nurse", region: "mixed", category: "General life", difficulty: "easy", metadata: { a: "Doctor", b: "Nurse" } },
  { gameSlug: "traitors", contentType: "pair", title: "Teacher / Professor", region: "mixed", category: "General life", difficulty: "medium", metadata: { a: "Teacher", b: "Professor" } },
  { gameSlug: "traitors", contentType: "pair", title: "Landlord / Neighbour", region: "mixed", category: "General life", difficulty: "medium", metadata: { a: "Landlord", b: "Neighbour" } },
  { gameSlug: "traitors", contentType: "pair", title: "Gym / Yoga", region: "mixed", category: "General life", difficulty: "easy", metadata: { a: "Gym", b: "Yoga" } },
  { gameSlug: "traitors", contentType: "pair", title: "Chai / Coffee", region: "mixed", category: "Food", difficulty: "easy", metadata: { a: "Chai", b: "Coffee" } },
  { gameSlug: "traitors", contentType: "pair", title: "Samosa / Kachori", region: "mixed", category: "Food", difficulty: "easy", metadata: { a: "Samosa", b: "Kachori" } },
  { gameSlug: "traitors", contentType: "pair", title: "Biryani / Pulao", region: "mixed", category: "Food", difficulty: "easy", metadata: { a: "Biryani", b: "Pulao" } },
  { gameSlug: "traitors", contentType: "pair", title: "Dosa / Uttapam", region: "mixed", category: "Food", difficulty: "medium", metadata: { a: "Dosa", b: "Uttapam" } },
  { gameSlug: "traitors", contentType: "pair", title: "Rajma / Chole", region: "mixed", category: "Food", difficulty: "easy", metadata: { a: "Rajma", b: "Chole" } },
  { gameSlug: "traitors", contentType: "pair", title: "Paneer / Tofu", region: "mixed", category: "Food", difficulty: "medium", metadata: { a: "Paneer", b: "Tofu" } },
  { gameSlug: "traitors", contentType: "pair", title: "Pizza / Burger", region: "mixed", category: "Food", difficulty: "easy", metadata: { a: "Pizza", b: "Burger" } },
  { gameSlug: "traitors", contentType: "pair", title: "Momo / Spring roll", region: "mixed", category: "Food", difficulty: "easy", metadata: { a: "Momo", b: "Spring roll" } },
  { gameSlug: "traitors", contentType: "pair", title: "Lassi / Buttermilk", region: "mixed", category: "Food", difficulty: "medium", metadata: { a: "Lassi", b: "Buttermilk" } },
  { gameSlug: "traitors", contentType: "pair", title: "Gulab jamun / Rasgulla", region: "mixed", category: "Food", difficulty: "easy", metadata: { a: "Gulab jamun", b: "Rasgulla" } },
  { gameSlug: "traitors", contentType: "pair", title: "Maggi / Pasta", region: "mixed", category: "Food", difficulty: "easy", metadata: { a: "Maggi", b: "Pasta" } },
  { gameSlug: "traitors", contentType: "pair", title: "Vada pav / Pav bhaji", region: "mixed", category: "Food", difficulty: "easy", metadata: { a: "Vada pav", b: "Pav bhaji" } },
  { gameSlug: "traitors", contentType: "pair", title: "Rasode Mein Kaun Tha / Bachpan Ka Pyaar", region: "india", category: "Memes and internet, India", difficulty: "easy", metadata: { a: "Rasode Mein Kaun Tha", b: "Bachpan Ka Pyaar" } },
  { gameSlug: "traitors", contentType: "pair", title: "Binod / Moye Moye", region: "india", category: "Memes and internet, India", difficulty: "medium", metadata: { a: "Binod", b: "Moye Moye" } },
  { gameSlug: "traitors", contentType: "pair", title: "Pawri Ho Rahi Hai / Just Looking Like a Wow", region: "india", category: "Memes and internet, India", difficulty: "easy", metadata: { a: "Pawri Ho Rahi Hai", b: "Just Looking Like a Wow" } },
  { gameSlug: "traitors", contentType: "pair", title: "Sharma Ji Ka Beta / Log Kya Kahenge", region: "india", category: "Memes and internet, India", difficulty: "easy", metadata: { a: "Sharma Ji Ka Beta", b: "Log Kya Kahenge" } },
  { gameSlug: "traitors", contentType: "pair", title: "Babu Bhaiya / Raju", region: "india", category: "Memes and internet, India", difficulty: "medium", metadata: { a: "Babu Bhaiya", b: "Raju" } },
  { gameSlug: "traitors", contentType: "pair", title: "CarryMinati / Bhuvan Bam", region: "india", category: "Memes and internet, India", difficulty: "easy", metadata: { a: "CarryMinati", b: "Bhuvan Bam" } },
  { gameSlug: "traitors", contentType: "pair", title: "Ashish Chanchlani / Harsh Beniwal", region: "india", category: "Memes and internet, India", difficulty: "medium", metadata: { a: "Ashish Chanchlani", b: "Harsh Beniwal" } },
  { gameSlug: "traitors", contentType: "pair", title: "Dhinchak Pooja / Taher Shah", region: "india", category: "Memes and internet, India", difficulty: "medium", metadata: { a: "Dhinchak Pooja", b: "Taher Shah" } },
  { gameSlug: "traitors", contentType: "pair", title: "Orkut / Hi5", region: "india", category: "Memes and internet, India", difficulty: "hard", metadata: { a: "Orkut", b: "Hi5" } },
  { gameSlug: "traitors", contentType: "pair", title: "Nokia 3310 / BlackBerry", region: "india", category: "Memes and internet, India", difficulty: "easy", metadata: { a: "Nokia 3310", b: "BlackBerry" } },
  { gameSlug: "traitors", contentType: "pair", title: "ShareChat / Moj", region: "india", category: "Memes and internet, India", difficulty: "hard", metadata: { a: "ShareChat", b: "Moj" } },
  { gameSlug: "traitors", contentType: "pair", title: "Distracted Boyfriend / Drakeposting", region: "global", category: "Memes and internet, global", difficulty: "easy", metadata: { a: "Distracted Boyfriend", b: "Drakeposting" } },
  { gameSlug: "traitors", contentType: "pair", title: "This Is Fine / Surprised Pikachu", region: "global", category: "Memes and internet, global", difficulty: "easy", metadata: { a: "This Is Fine", b: "Surprised Pikachu" } },
  { gameSlug: "traitors", contentType: "pair", title: "Doge / Grumpy Cat", region: "global", category: "Memes and internet, global", difficulty: "easy", metadata: { a: "Doge", b: "Grumpy Cat" } },
  { gameSlug: "traitors", contentType: "pair", title: "Rickroll / Nyan Cat", region: "global", category: "Memes and internet, global", difficulty: "medium", metadata: { a: "Rickroll", b: "Nyan Cat" } },
  { gameSlug: "traitors", contentType: "pair", title: "Instagram Reels / YouTube Shorts", region: "global", category: "Memes and internet, global", difficulty: "easy", metadata: { a: "Instagram Reels", b: "YouTube Shorts" } },
  { gameSlug: "traitors", contentType: "pair", title: "Woman Yelling at a Cat / Two Buttons", region: "global", category: "Memes and internet, global", difficulty: "medium", metadata: { a: "Woman Yelling at a Cat", b: "Two Buttons" } },
  { gameSlug: "traitors", contentType: "pair", title: "Pepe the Frog / Wojak", region: "global", category: "Memes and internet, global", difficulty: "medium", metadata: { a: "Pepe the Frog", b: "Wojak" } },
  { gameSlug: "traitors", contentType: "pair", title: "Harlem Shake / Gangnam Style", region: "global", category: "Memes and internet, global", difficulty: "easy", metadata: { a: "Harlem Shake", b: "Gangnam Style" } },
  { gameSlug: "traitors", contentType: "pair", title: "Ice Bucket Challenge / Mannequin Challenge", region: "global", category: "Memes and internet, global", difficulty: "easy", metadata: { a: "Ice Bucket Challenge", b: "Mannequin Challenge" } },
  { gameSlug: "traitors", contentType: "pair", title: "Planking / Dabbing", region: "global", category: "Memes and internet, global", difficulty: "easy", metadata: { a: "Planking", b: "Dabbing" } },
  { gameSlug: "traitors", contentType: "pair", title: "Skibidi Toilet / Ohio", region: "global", category: "Memes and internet, global", difficulty: "medium", metadata: { a: "Skibidi Toilet", b: "Ohio" } },
  { gameSlug: "traitors", contentType: "pair", title: "Cricket World Cup / IPL Final", region: "mixed", category: "Events", difficulty: "easy", metadata: { a: "Cricket World Cup", b: "IPL Final" } },
  { gameSlug: "traitors", contentType: "pair", title: "Olympics / Commonwealth Games", region: "mixed", category: "Events", difficulty: "easy", metadata: { a: "Olympics", b: "Commonwealth Games" } },
  { gameSlug: "traitors", contentType: "pair", title: "FIFA World Cup / UEFA Champions League", region: "mixed", category: "Events", difficulty: "easy", metadata: { a: "FIFA World Cup", b: "UEFA Champions League" } },
  { gameSlug: "traitors", contentType: "pair", title: "Diwali / Holi", region: "mixed", category: "Events", difficulty: "easy", metadata: { a: "Diwali", b: "Holi" } },
  { gameSlug: "traitors", contentType: "pair", title: "New Year / Christmas", region: "mixed", category: "Events", difficulty: "easy", metadata: { a: "New Year", b: "Christmas" } },
  { gameSlug: "traitors", contentType: "pair", title: "Independence Day / Republic Day", region: "mixed", category: "Events", difficulty: "medium", metadata: { a: "Independence Day", b: "Republic Day" } },
  { gameSlug: "traitors", contentType: "pair", title: "Ganesh Chaturthi / Durga Puja", region: "mixed", category: "Events", difficulty: "medium", metadata: { a: "Ganesh Chaturthi", b: "Durga Puja" } },
  { gameSlug: "traitors", contentType: "pair", title: "Oscars / Grammys", region: "mixed", category: "Events", difficulty: "easy", metadata: { a: "Oscars", b: "Grammys" } },
  { gameSlug: "traitors", contentType: "pair", title: "WhatsApp / Telegram", region: "mixed", category: "Apps and brands", difficulty: "easy", metadata: { a: "WhatsApp", b: "Telegram" } },
  { gameSlug: "traitors", contentType: "pair", title: "Instagram / Snapchat", region: "mixed", category: "Apps and brands", difficulty: "easy", metadata: { a: "Instagram", b: "Snapchat" } },
  { gameSlug: "traitors", contentType: "pair", title: "Zomato / Swiggy", region: "mixed", category: "Apps and brands", difficulty: "easy", metadata: { a: "Zomato", b: "Swiggy" } },
  { gameSlug: "traitors", contentType: "pair", title: "Ola / Uber", region: "mixed", category: "Apps and brands", difficulty: "easy", metadata: { a: "Ola", b: "Uber" } },
  { gameSlug: "traitors", contentType: "pair", title: "Netflix / Prime Video", region: "mixed", category: "Apps and brands", difficulty: "easy", metadata: { a: "Netflix", b: "Prime Video" } },
  { gameSlug: "traitors", contentType: "pair", title: "Paytm / PhonePe", region: "mixed", category: "Apps and brands", difficulty: "easy", metadata: { a: "Paytm", b: "PhonePe" } },
  { gameSlug: "traitors", contentType: "pair", title: "Amazon / Flipkart", region: "mixed", category: "Apps and brands", difficulty: "easy", metadata: { a: "Amazon", b: "Flipkart" } },
  { gameSlug: "traitors", contentType: "pair", title: "Nike / Adidas", region: "mixed", category: "Apps and brands", difficulty: "easy", metadata: { a: "Nike", b: "Adidas" } },
  { gameSlug: "traitors", contentType: "pair", title: "Sacred Games / Mirzapur", region: "india", category: "Shows and films, India", difficulty: "easy", metadata: { a: "Sacred Games", b: "Mirzapur" } },
  { gameSlug: "traitors", contentType: "pair", title: "Panchayat / Gullak", region: "india", category: "Shows and films, India", difficulty: "easy", metadata: { a: "Panchayat", b: "Gullak" } },
  { gameSlug: "traitors", contentType: "pair", title: "Kota Factory / Aspirants", region: "india", category: "Shows and films, India", difficulty: "easy", metadata: { a: "Kota Factory", b: "Aspirants" } },
  { gameSlug: "traitors", contentType: "pair", title: "The Family Man / Special Ops", region: "india", category: "Shows and films, India", difficulty: "easy", metadata: { a: "The Family Man", b: "Special Ops" } },
  { gameSlug: "traitors", contentType: "pair", title: "Paatal Lok / Delhi Crime", region: "india", category: "Shows and films, India", difficulty: "easy", metadata: { a: "Paatal Lok", b: "Delhi Crime" } },
  { gameSlug: "traitors", contentType: "pair", title: "Scam 1992 / Rocket Boys", region: "india", category: "Shows and films, India", difficulty: "medium", metadata: { a: "Scam 1992", b: "Rocket Boys" } },
  { gameSlug: "traitors", contentType: "pair", title: "Farzi / Jamtara", region: "india", category: "Shows and films, India", difficulty: "medium", metadata: { a: "Farzi", b: "Jamtara" } },
  { gameSlug: "traitors", contentType: "pair", title: "Baahubali / RRR", region: "india", category: "Shows and films, India", difficulty: "easy", metadata: { a: "Baahubali", b: "RRR" } },
  { gameSlug: "traitors", contentType: "pair", title: "Zindagi Na Milegi Dobara / Dil Chahta Hai", region: "india", category: "Shows and films, India", difficulty: "easy", metadata: { a: "Zindagi Na Milegi Dobara", b: "Dil Chahta Hai" } },
  { gameSlug: "traitors", contentType: "pair", title: "Dangal / Chak De India", region: "india", category: "Shows and films, India", difficulty: "easy", metadata: { a: "Dangal", b: "Chak De India" } },
  { gameSlug: "traitors", contentType: "pair", title: "Taarak Mehta Ka Ooltah Chashmah / Bhabhi Ji Ghar Par Hain", region: "india", category: "Shows and films, India", difficulty: "easy", metadata: { a: "Taarak Mehta Ka Ooltah Chashmah", b: "Bhabhi Ji Ghar Par Hain" } },
  { gameSlug: "traitors", contentType: "pair", title: "Ramayan / Mahabharat", region: "india", category: "Shows and films, India", difficulty: "medium", metadata: { a: "Ramayan", b: "Mahabharat" } },
  { gameSlug: "traitors", contentType: "pair", title: "Game of Thrones / House of the Dragon", region: "global", category: "Shows and films, global", difficulty: "medium", metadata: { a: "Game of Thrones", b: "House of the Dragon" } },
  { gameSlug: "traitors", contentType: "pair", title: "Friends / How I Met Your Mother", region: "global", category: "Shows and films, global", difficulty: "easy", metadata: { a: "Friends", b: "How I Met Your Mother" } },
  { gameSlug: "traitors", contentType: "pair", title: "Stranger Things / Dark", region: "global", category: "Shows and films, global", difficulty: "medium", metadata: { a: "Stranger Things", b: "Dark" } },
  { gameSlug: "traitors", contentType: "pair", title: "Money Heist / Squid Game", region: "global", category: "Shows and films, global", difficulty: "easy", metadata: { a: "Money Heist", b: "Squid Game" } },
  { gameSlug: "traitors", contentType: "pair", title: "Breaking Bad / Better Call Saul", region: "global", category: "Shows and films, global", difficulty: "easy", metadata: { a: "Breaking Bad", b: "Better Call Saul" } },
  { gameSlug: "traitors", contentType: "pair", title: "The Office / Parks and Recreation", region: "global", category: "Shows and films, global", difficulty: "easy", metadata: { a: "The Office", b: "Parks and Recreation" } },
  { gameSlug: "traitors", contentType: "pair", title: "Narcos / Peaky Blinders", region: "global", category: "Shows and films, global", difficulty: "medium", metadata: { a: "Narcos", b: "Peaky Blinders" } },
  { gameSlug: "traitors", contentType: "pair", title: "The Boys / Invincible", region: "global", category: "Shows and films, global", difficulty: "easy", metadata: { a: "The Boys", b: "Invincible" } },
  { gameSlug: "traitors", contentType: "pair", title: "Interstellar / Inception", region: "global", category: "Shows and films, global", difficulty: "easy", metadata: { a: "Interstellar", b: "Inception" } },
  { gameSlug: "traitors", contentType: "pair", title: "Fast and Furious / Mission Impossible", region: "global", category: "Shows and films, global", difficulty: "easy", metadata: { a: "Fast and Furious", b: "Mission Impossible" } },
  { gameSlug: "traitors", contentType: "pair", title: "Ass / Boobs", region: "mixed", category: "Adult", difficulty: "easy", metadata: { a: "Ass", b: "Boobs", adult: true } },
  { gameSlug: "traitors", contentType: "pair", title: "Tinder / Bumble", region: "mixed", category: "Adult", difficulty: "easy", metadata: { a: "Tinder", b: "Bumble", adult: true } },
  { gameSlug: "traitors", contentType: "pair", title: "One night stand / Situationship", region: "mixed", category: "Adult", difficulty: "easy", metadata: { a: "One night stand", b: "Situationship", adult: true } },
  { gameSlug: "traitors", contentType: "pair", title: "Ex / Crush", region: "mixed", category: "Adult", difficulty: "easy", metadata: { a: "Ex", b: "Crush", adult: true } },
  { gameSlug: "traitors", contentType: "pair", title: "Nudes / Thirst trap", region: "mixed", category: "Adult", difficulty: "medium", metadata: { a: "Nudes", b: "Thirst trap", adult: true } },
  { gameSlug: "traitors", contentType: "pair", title: "Condom / Birth control pill", region: "mixed", category: "Adult", difficulty: "easy", metadata: { a: "Condom", b: "Birth control pill", adult: true } },
  { gameSlug: "traitors", contentType: "pair", title: "Vodka shot / Tequila shot", region: "mixed", category: "Adult", difficulty: "easy", metadata: { a: "Vodka shot", b: "Tequila shot", adult: true } },
  { gameSlug: "traitors", contentType: "pair", title: "Hangover / Blackout", region: "mixed", category: "Adult", difficulty: "medium", metadata: { a: "Hangover", b: "Blackout", adult: true } },
  { gameSlug: "traitors", contentType: "pair", title: "Strip club / Bar", region: "mixed", category: "Adult", difficulty: "easy", metadata: { a: "Strip club", b: "Bar", adult: true } },
  { gameSlug: "traitors", contentType: "pair", title: "Playboy / OnlyFans", region: "mixed", category: "Adult", difficulty: "easy", metadata: { a: "Playboy", b: "OnlyFans", adult: true } },
  { gameSlug: "traitors", contentType: "pair", title: "Virgin / Player", region: "mixed", category: "Adult", difficulty: "medium", metadata: { a: "Virgin", b: "Player", adult: true } },
  { gameSlug: "traitors", contentType: "pair", title: "Makeout / Cuddle", region: "mixed", category: "Adult", difficulty: "medium", metadata: { a: "Makeout", b: "Cuddle", adult: true } },
];
